apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notes-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/gartmeier/notes.git
    targetRevision: main
    path: helm/frontend
    helm:
      valuesObject:
        image:
          tag: "91f4d4e8"
        ingress:
          host: notes.gartmeier.dev
  destination:
    server: https://kubernetes.default.svc
    namespace: notes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
