apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.*
    helm:
      valuesObject:
        config:
          registries:
            - name: GitLab
              prefix: registry.gitlab.com
              api_url: https://registry.gitlab.com
              credentials: pullsecret:argocd/gitlab-registry-creds
              defaultns: library
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
