apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notes-keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/gartmeier/notes.git
    targetRevision: main
    path: k8s/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: notes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
