apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 72.6.2
    chart: kube-prometheus-stack
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        grafana:
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - notes-monitoring.gartmeier.dev
            tls:
              - secretName: grafana-tls
                hosts:
                  - notes-monitoring.gartmeier.dev
          grafana.ini:
            explore:
              enabled: true
            database:
              type: postgres
              host: notes-postgresql.notes:5432
              name: grafana
              user: $__env{GF_DATABASE_USER}
              password: $__env{GF_DATABASE_PASSWORD}
          envValueFrom:
            GF_DATABASE_USER:
              secretKeyRef:
                name: grafana-db
                key: user
            GF_DATABASE_PASSWORD:
              secretKeyRef:
                name: grafana-db
                key: password
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
        prometheus:
          prometheusSpec:
            retention: 7d
            serviceMonitorSelectorNilUsesHelmValues: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
