apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 72.6.2
    chart: kube-prometheus-stack
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        grafana:
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - notes-monitoring.gartmeier.dev
            tls:
              - secretName: grafana-tls
                hosts:
                  - notes-monitoring.gartmeier.dev
          grafana.ini:
            explore:
              enabled: true
          envValueFrom:
            GF_DATABASE_TYPE:
              secretKeyRef:
                name: grafana-db
                key: type
            GF_DATABASE_HOST:
              secretKeyRef:
                name: grafana-db
                key: host
            GF_DATABASE_NAME:
              secretKeyRef:
                name: grafana-db
                key: name
            GF_DATABASE_USER:
              secretKeyRef:
                name: grafana-db
                key: user
            GF_DATABASE_PASSWORD:
              secretKeyRef:
                name: grafana-db
                key: password
          additionalDataSources:
            - name: Loki
              type: loki
              uid: loki
              access: proxy
              url: http://loki-gateway.monitoring.svc.cluster.local
              isDefault: false
              editable: false
            - name: Tempo
              type: tempo
              uid: tempo
              access: proxy
              url: http://tempo.monitoring.svc.cluster.local:3100
              isDefault: false
              editable: false
          sidecar:
            datasources:
              enabled: true
              initDatasources: true
            dashboards:
              enabled: true
              searchNamespace: ALL
        prometheus:
          prometheusSpec:
            retention: 7d
            serviceMonitorSelectorNilUsesHelmValues: false
            enableRemoteWriteReceiver: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
