apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notes-postgresql
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "*"
    helm:
      valuesObject:
        auth:
          username: postgres
          password: postgres
          database: notes
        primary:
          persistence:
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: notes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
